### ISSUE TITLE
Incomplete requirements.txt

### ISSUE THREAD

**Issue by gnestlinger** [tianyilim/RRTx#1]
Could you please update the requirements.txt file to contain all required packages? Maybe even including the required version?
I tried the following, but unfortunately `pip install -r requirements.txt` failed.
- shapely
- scipy
- numpy
- matplotlib
- datetime
- commonroad-all
- dg_commons

**Comment by tianyilim** [comment]
Hi, unfortunately as mentioned in the README:

> Unfortunately the algorithm only works in the Docker environment specified for the assignment, so you would need to adapt the sample code to your specific use case.

However, if you do end up managing to use the codebase somehow in its current form, it'd be pretty cool.

I can of course add these as dependencies in `requirements.txt` but don't have the bandwidth to test / maintain it right now.
